### ISSUE TITLE
Add Swift 5.7 support?

### ISSUE THREAD

**Issue by Kedar-27** [gokulrajanpillai/Perfectionist#4]
Hi, can I submit new pr for hacktoberfest

**Comment by gokulrajanpillai** [comment]
Hi Kedar-27 sure, go ahead. I will update the labels.

**Comment by InsanelyHarsh** [comment]
I would like to take on this task.

**Comment by Kedar-27** [comment]
#5

**Comment by Kedar-27** [comment]
Have fixed this in #5   @gokulrajanpillai , please check this

**Comment by InsanelyHarsh** [comment]
Great! Is there any other task on which I can work?

**Comment by Kedar-27** [comment]
Yeah, maybe u can customise the UI or implement new screen in SwiftUI

**Comment by InsanelyHarsh** [comment]
Good for me, can you elaborate task more?

**Comment by InsanelyHarsh** [comment]
What is the minimum iOS Deployment Target you are targeting?

**Comment by Kedar-27** [comment]
Since it's SwiftUI better to support latest possible i.e. 16

**Comment by Kedar-27** [comment]
@InsanelyHarsh can you implement the existing screen grocerylist and qr scanner screen in SwiftUI ?

**Comment by InsanelyHarsh** [comment]
Okay, Can you make a new Issue and assign me?

**Comment by gokulrajanpillai** [comment]
Thanks @Kedar-27 for your contribution!
Closing the issue as this is merged with PR:

https://github.com/gokulrajanpillai/Perfectionist/pull/5
