### ISSUE TITLE
SwiftUI Support

### ISSUE THREAD

**Issue by Kedar-27** [gokulrajanpillai/Perfectionist#6]
@InsalyHarsh

**Comment by Kedar-27** [comment]
@InsanelyHarsh

**Comment by gokulrajanpillai** [comment]
@InsalyHarsh If you are interested in picking up the topic, I can add you as a contributor to the project.

@Kedar-27 @InsalyHarsh
I would also recommend creating a feature inside the project, so it can be linked into this issue.
If you want to fork, make sure to create a feature branch inside the project reflecting those changes. This way we can link the pull request to the issue, so it automatically get closed with the PullRequest.

**Comment by Kedar-27** [comment]
Sure

**Comment by InsanelyHarsh** [comment]
Hello @gokulrajanpillai @Kedar-27,
I have updated all the views from the storyboard to SwiftUI & tweaked UI.


Updated UI Screenshots:
<img src="https://user-images.githubusercontent.com/98019495/193474259-79399291-1a0f-4fc4-b48d-59455257f957.png" width="225" height="420">

<img src="https://user-images.githubusercontent.com/98019495/193474263-d4cddbe9-1a08-43a1-9db9-a9a73d08e055.png" width="225" height="420">

<img src="https://user-images.githubusercontent.com/98019495/193474248-ca68787d-3685-4fa1-bfde-37922c73c7d4.png" width="225" height="420">

<img src="https://user-images.githubusercontent.com/98019495/193474256-79acd846-92f9-4605-b68e-be9c876bfea4.png" width="225" height="420">

**Comment by Kedar-27** [comment]
@InsanelyHarsh looks perfect...great job

**Comment by gokulrajanpillai** [comment]
PR is merged: https://github.com/gokulrajanpillai/Perfectionist/pull/7

**Comment by gokulrajanpillai** [comment]
Thanks @InsanelyHarsh for your contribution!

**Comment by InsanelyHarsh** [comment]
Hello @gokulrajanpillai,
I have made a new PR with an updated Branch can you Review and merge it?
